name: Build

on:
  push:
    branches: [ '**' ]  # To run on any branch
  pull_request:
    branches: [ '**' ]  # To run on any branch
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (e.g., 1.0.0)'
        required: true
        default: '0.0.0'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true

    - name: Install dependencies (ubuntu only)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

    - name: Install dependencies (macOS only)
      if: matrix.os == 'macos-latest'
      run: |
        brew install gtk+3 webkit2gtk3 libappindicator

    - name: Install app dependencies and build web
      run: yarn && yarn build

    - name: Build Tauri app
      uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tagName: v__VERSION__
        releaseName: "App v__VERSION__"
        releaseBody: "See the assets to download this version and install."
        releaseDraft: true
        prerelease: false
        args: --target ${{ matrix.target }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: meroctl-${{ matrix.target }}
        path: |
          src-tauri/target/${{ matrix.target }}/release/bundle/dmg/*
          src-tauri/target/${{ matrix.target }}/release/bundle/deb/*
          src-tauri/target/${{ matrix.target }}/release/bundle/appimage/*